### ISSUE TITLE
任务执行有效期问题

### ISSUE THREAD

**Issue by putyy** [yunwuxin/think-cron#14]
yunwuxin\cron\command::serverShouldRun
代码里面的意思是只缓存60s 这样感觉不是很科学哦，比如定时推送微信模板消息类的肯定不止60s吧

 yunwuxin\cron\Task::onOneServer属性怎么不默认为true呢？

**Comment by yunwuxin** [comment]
计划任务的执行最小周期就是60s，这里的检查不影响后面任务是否真的被执行，任务执行的时候还会检查withoutOverlapping、expiresAt等属性，但是计划任务里不建议执行很长时间的操作，可以推到队列里去执行，因为计划任务是不会等待任务执行完成的，不然一个任务超时了，会影响后面所有的任务
onOneServer的配置 需要你的cache支持  比如cache是file驱动的话 就不行，需要是redis这类

**Comment by putyy** [comment]
嗯嗯 我又看了下源码 没问题
