### ISSUE TITLE
请问每隔6小时如何表示呢？与crontab是否一致？

### ISSUE THREAD

**Issue by jayazhao** [yunwuxin/think-cron#3]
你好，我在代码中是根据crontab设置的：
`$this->expression('0 */6 * * *');`

但是我查看了 think-cron 包的 `$expression` 变量默认是 6 个 * 号，请问自定义的时间应该怎么表示呢？

**Comment by yunwuxin** [comment]
与 crontab  一致

**Comment by jayazhao** [comment]
非常感谢
