### ISSUE TITLE
采用循环的方式是不是会有同步阻塞的问题

### ISSUE THREAD

**Issue by jadechenlei** [yunwuxin/think-cron#4]
如果上一个脚本一直死循环，是不是就走不到后面的脚本了？

**Comment by yunwuxin** [comment]
每分钟启动一个新的进程执行任务的   每个进程只执行一个任务

**Comment by jadechenlei** [comment]
您好
举个例子，有两个子任务都是设定的每分钟执行一次。
Task1执行了2分钟，那么task2岂不是要等task1执行完了才能被执行?（就是说当前这分钟根本不会执行task2)

`//采用循环的方式执行,每次都需要等待上个任务执行完，才能执行下个任务`
