### ISSUE TITLE
能写清楚，到底是：5.0的还是5.1的?

### ISSUE THREAD

**Issue by hulang** [yunwuxin/think-cron#5]
RT

**Comment by hulang** [comment]
好吧，5.0的，5.1的什么时候出？能写点具体的demo。。。或者，这个有哪些开源项目用到了。我去看看具体用法！！！！！

**Comment by hulang** [comment]
了解，ManagesFrequencies里面的spliceIntoPosition方法，为什么不是public
我想每3分钟，4分钟，6分钟执行。。都是固定了。。。

**Comment by hulang** [comment]
希望更好的支持:
*/3 * * * *
30 1 * * *
这样自定义！！！

**Comment by liu21st** [comment]
有其它问题最好重新开issue
