### ISSUE TITLE
当有一个task发生异常错误后续的task就不会执行下去

### ISSUE THREAD

**Issue by oyrm** [yunwuxin/think-cron#9]
![image](https://user-images.githubusercontent.com/8858258/72591521-49aab780-393b-11ea-8d96-1b1283c085eb.png)

如上图，我后面还有十几个task，当其中一个发生异常，后续的task没有运行了

**Comment by iamssn** [comment]
你接管一下异常不就好了?

**Comment by yunwuxin** [comment]
已处理
